# arguments for dataset
dataset: FSSG
nclass: 11 
crop_size: 518
data_root:   #Fill in the dataset root path


epochs: 240
batch_size: 2
lr: 0.000005
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: dpt
backbone: dinov2_small
lock_backbone: False
