dataset: FSSG
data_root: /path/to/FSSG
nclass: 11

model: dpt
backbone: dinov2_small
pretrained_path: pretrained/dinov2_small.pth
lock_backbone: false

lr: 0.000005
lr_multi: 40.0

criterion:
  name: CELoss
  kwargs:
    ignore_index: 255

grid_size: 32
reliability_threshold: 0.4
lambda_u: 1.0
warmup_epochs: 15

epochs: 240
batch_size: 2
crop_size: 518
